apiVersion: apps/v1
kind: Deployment
metadata:
  name: yumi-app-deployment
  labels:
    app: yumi-app

spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: yumi-app

  template:
    metadata:
      labels:
        app: yumi-app
    spec:
      containers:
        - name: yumi-app
          image: bartee/yumi-app:1.4.0
          ports:
            - containerPort: 9999
              name: http
